from __future__ import annotations

SOCKET_AM4_V1       = "AM4_V1"
SOCKET_FT5_FP5_AM4  = "FT5_FP5_AM4"
SOCKET_AM4_V2       = "AM4_V2"
SOCKET_FP6_AM4      = "FP6_AM4"
SOCKET_FF3          = "FF3"
SOCKET_FT6_FP7_FP8  = "FT6_FP7_FP8"
SOCKET_AM5_V1       = "AM5_V1"

_FAMILY_SOCKET: dict[str, str] = {
    "SummitRidge":     SOCKET_AM4_V1,
    "PinnacleRidge":   SOCKET_AM4_V1,
    "RavenRidge":      SOCKET_FT5_FP5_AM4,
    "Picasso":         SOCKET_FT5_FP5_AM4,
    "Dali":            SOCKET_FT5_FP5_AM4,
    "Pollock":         SOCKET_FT5_FP5_AM4,
    "FireFlight":      SOCKET_FT5_FP5_AM4,
    "Matisse":         SOCKET_AM4_V2,
    "Renoir":          SOCKET_FP6_AM4,
    "Lucienne":        SOCKET_FP6_AM4,
    "Cezanne_Barcelo": SOCKET_FP6_AM4,
    "VanGogh":         SOCKET_FF3,
    "Mendocino":       SOCKET_FT6_FP7_FP8,
    "Vermeer":         SOCKET_AM4_V2,
    "Rembrandt":       SOCKET_FT6_FP7_FP8,
    "Raphael":         SOCKET_AM5_V1,
    "DragonRange":     SOCKET_AM5_V1,
    "PhoenixPoint":    SOCKET_FT6_FP7_FP8,
    "PhoenixPoint2":   SOCKET_FT6_FP7_FP8,
    "HawkPoint":       SOCKET_FT6_FP7_FP8,
    "HawkPoint2":      SOCKET_FT6_FP7_FP8,
    "SonomaValley":    SOCKET_FT6_FP7_FP8,
    "GraniteRidge":    SOCKET_AM5_V1,
    "FireRange":       SOCKET_AM5_V1,
    "StrixHalo":       SOCKET_FT6_FP7_FP8,
    "StrixPoint":      SOCKET_FT6_FP7_FP8,
    "KrackanPoint":    SOCKET_FT6_FP7_FP8,
    "KrackanPoint2":   SOCKET_FT6_FP7_FP8,
}

_CMD_AM4_V1: list[tuple[str, bool, int]] = [
    ("ppt-limit",                          False, 0x64),
    ("ppt-limit",                          True,  0x31),
    ("tdc-limit",                          False, 0x65),
    ("edc-limit",                          False, 0x66),
    ("tctl-temp",                          False, 0x68),
    ("pbo-scalar",                         False, 0x6a),
    ("oc-clk",                             False, 0x6c),
    ("oc-clk",                             True,  0x39),
    ("per-core-oc-clk",                    False, 0x6d),
    ("oc-volt",                            False, 0x6e),
    ("oc-volt",                            True,  0x38),
    ("enable-oc",                          True,  0x23),
    ("enable-oc",                          False, 0x6b),
    ("disable-oc",                         True,  0x24),
    ("get-sustained-power-and-thm-limit",  True,  0x36),
    ("setcpu-freqto-ramstate",             True,  0x23),
    ("stopcpu-freqto-ramstate",            True,  0x24),
    ("stopcpu-freqto-ramstate",            True,  0x25),
]

_CMD_FT5_FP5_AM4: list[tuple[str, bool, int]] = [
    ("enable-feature",                     True,  0x05),
    ("disable-feature",                    True,  0x06),
    ("stapm-limit",                        True,  0x1a),
    ("stapm-limit",                        False, 0x2e),
    ("stapm-time",                         True,  0x1e),
    ("stapm-time",                         False, 0x32),
    ("fast-limit",                         True,  0x1b),
    ("fast-limit",                         False, 0x30),
    ("slow-limit",                         True,  0x1c),
    ("slow-limit",                         False, 0x2f),
    ("slow-time",                          True,  0x1d),
    ("slow-time",                          False, 0x31),
    ("tctl-temp",                          True,  0x1f),
    ("tctl-temp",                          False, 0x33),
    ("chtc-temp",                          False, 0x56),
    ("vrm-current",                        True,  0x20),
    ("vrm-current",                        False, 0x34),
    ("vrmmax-current",                     True,  0x22),
    ("vrmmax-current",                     False, 0x36),
    ("vrmsoc-current",                     True,  0x21),
    ("vrmsoc-current",                     False, 0x35),
    ("vrmsocmax-current",                  True,  0x23),
    ("vrmsocmax-current",                  False, 0x37),
    ("psi0-current",                       True,  0x24),
    ("psi0-current",                       False, 0x38),
    ("psi0soc-current",                    True,  0x25),
    ("psi0soc-current",                    False, 0x39),
    ("prochot-deassertion-ramp",           True,  0x26),
    ("prochot-deassertion-ramp",           False, 0x3a),
    ("power-saving",                       True,  0x19),
    ("max-performance",                    True,  0x18),
    ("enable-oc",                          True,  0x58),
    ("disable-oc",                         True,  0x3f),
    ("oc-clk",                             False, 0x7d),
    ("per-core-oc-clk",                    False, 0x7e),
    ("oc-clk",                             True,  0x59),
    ("per-core-oc-clk",                    True,  0x5a),
    ("oc-clk",                             True,  0x41),
    ("oc-volt",                            True,  0x5b),
    ("oc-volt",                            False, 0x7c),
    ("oc-volt",                            True,  0x40),
    ("set-gpuclockoverdrive-byvid",        True,  0x3d),
    ("set-gpuclockoverdrive-byvid",        False, 0x61),
    ("pbo-scalar",                         True,  0x57),
    ("pbo-scalar",                         False, 0x63),
    ("get-pbo-scalar",                     False, 0x62),
    ("max-cpuclk",                         True,  0x44),
    ("min-cpuclk",                         True,  0x45),
    ("max-gfxclk",                         True,  0x46),
    ("max-gfxclk",                         False, 0x68),
    ("min-gfxclk",                         True,  0x47),
    ("min-gfxclk",                         False, 0x69),
    ("max-socclk-frequency",               True,  0x48),
    ("max-socclk-frequency",               False, 0x66),
    ("min-socclk-frequency",               True,  0x49),
    ("min-socclk-frequency",               False, 0x67),
    ("max-fclk-frequency",                 True,  0x4a),
    ("min-fclk-frequency",                 True,  0x4b),
    ("max-vcn",                            True,  0x4c),
    ("min-vcn",                            True,  0x4d),
    ("max-lclk",                           True,  0x4e),
    ("min-lclk",                           True,  0x4f),
    ("set-coper",                          False, 0x58),
    ("set-coall",                          False, 0x59),
    ("set-cogfx",                          False, 0x59),
    ("setcpu-freqto-ramstate",             True,  0x2f),
    ("stopcpu-freqto-ramstate",            True,  0x30),
    ("stopcpu-freqto-ramstate",            True,  0x31),
    ("set-ulv-vid",                        True,  0x35),
    ("set-vddoff-vid",                     True,  0x3a),
    ("set-vmin-freq",                      True,  0x3b),
    ("get-sustained-power-and-thm-limit",  True,  0x43),
    ("get-sustained-power-and-thm-limit",  False, 0x65),
    ("get-pbo-fused-power-limit",          False, 0x7f),
    ("get-pbo-fused-slow-limit",           False, 0x80),
    ("get-pbo-fused-fast-limit",           False, 0x81),
    ("get-pbo-fused-apu-slow-limit",       False, 0x82),
    ("get-pbo-fused-vrmtdc-limit",         False, 0x83),
    ("get-pbo-fused-vrmsoc-current",       False, 0x84),
]

_CMD_AM4_V2: list[tuple[str, bool, int]] = [
    ("enable-feature",                     True,  0x03),
    ("disable-feature",                    True,  0x04),
    ("ppt-limit",                          True,  0x3d),
    ("ppt-limit",                          False, 0x53),
    ("tdc-limit",                          True,  0x3b),
    ("tdc-limit",                          False, 0x54),
    ("edc-limit",                          True,  0x3c),
    ("edc-limit",                          False, 0x55),
    ("tctl-temp",                          True,  0x3e),
    ("tctl-temp",                          False, 0x56),
    ("pbo-scalar",                         False, 0x58),
    ("oc-clk",                             True,  0x26),
    ("oc-clk",                             False, 0x5c),
    ("per-core-oc-clk",                    True,  0x27),
    ("per-core-oc-clk",                    False, 0x5d),
    ("oc-volt",                            True,  0x28),
    ("oc-volt",                            False, 0x61),
    ("set-coall",                          True,  0x36),
    ("set-coall",                          False, 0x0b),
    ("set-coper",                          True,  0x35),
    ("set-coper",                          False, 0x0a),
    ("enable-oc",                          True,  0x24),
    ("enable-oc",                          False, 0x5a),
    ("disable-oc",                         True,  0x25),
    ("disable-oc",                         False, 0x5b),
    ("set-boost-limit-frequency",          True,  0x2b),
    ("get-pbo-scalar",                     False, 0x6c),
    ("get-sustained-power-and-thm-limit",  True,  0x23),
    ("get-overclocking-support",           False, 0x6f),
    ("get-coper-options",                  False, 0x7c),
]

_CMD_FP6_AM4: list[tuple[str, bool, int]] = [
    ("enable-feature",                     True,  0x05),
    ("disable-feature",                    True,  0x07),
    ("stapm-limit",                        True,  0x14),
    ("stapm-limit",                        False, 0x31),
    ("ppt-limit",                          False, 0x33),
    ("stapm-time",                         True,  0x18),
    ("stapm-time",                         False, 0x36),
    ("fast-limit",                         True,  0x15),
    ("fast-limit",                         False, 0x32),
    ("slow-limit",                         True,  0x16),
    ("slow-limit",                         False, 0x33),
    ("slow-time",                          True,  0x17),
    ("slow-time",                          False, 0x35),
    ("tctl-temp",                          True,  0x19),
    ("chtc-temp",                          False, 0x37),
    ("apu-skin-temp",                      True,  0x38),
    ("apu-skin-temp",                      False, 0x91),
    ("dgpu-skin-temp",                     True,  0x39),
    ("dgpu-skin-temp",                     False, 0x92),
    ("vrm-current",                        True,  0x1a),
    ("vrm-current",                        False, 0x38),
    ("vrmmax-current",                     True,  0x1c),
    ("vrmmax-current",                     False, 0x3a),
    ("vrmsoc-current",                     True,  0x1b),
    ("vrmsoc-current",                     False, 0x39),
    ("vrmsocmax-current",                  True,  0x1d),
    ("vrmsocmax-current",                  False, 0x3b),
    ("psi0-current",                       True,  0x1e),
    ("psi0-current",                       False, 0x3c),
    ("psi0soc-current",                    True,  0x1f),
    ("psi0soc-current",                    False, 0x3d),
    ("prochot-deassertion-ramp",           True,  0x20),
    ("prochot-deassertion-ramp",           False, 0x3e),
    ("skin-temp-limit",                    True,  0x53),
    ("apu-slow-limit",                     True,  0x21),
    ("apu-slow-limit",                     False, 0x34),
    ("power-saving",                       True,  0x12),
    ("max-performance",                    True,  0x11),
    ("enable-oc",                          False, 0x17),
    ("enable-oc",                          True,  0x2f),
    ("disable-oc",                         False, 0x18),
    ("disable-oc",                         True,  0x30),
    ("oc-clk",                             True,  0x31),
    ("oc-clk",                             False, 0x19),
    ("per-core-oc-clk",                    True,  0x32),
    ("per-core-oc-clk",                    False, 0x1a),
    ("oc-volt",                            True,  0x33),
    ("oc-volt",                            False, 0x1b),
    ("set-gpuclockoverdrive-byvid",        True,  0x34),
    ("gfx-clk",                            False, 0x89),
    ("gfx-clk",                            False, 0x1c),
    ("pbo-scalar",                         True,  0x49),
    ("pbo-scalar",                         False, 0x3f),
    ("get-pbo-scalar",                     False, 0x0f),
    ("set-cogfx",                          False, 0x53),
    ("set-coper",                          True,  0x54),
    ("set-coper",                          False, 0x52),
    ("set-coall",                          True,  0x55),
    ("set-coall",                          False, 0xb1),
    ("get-coper-options",                  False, 0xc3),
    ("get-cogfx-options",                  False, 0xc6),
    ("get-sustained-power-and-thm-limit",  True,  0x5b),
    ("get-pbo-fused-power-limit",          False, 0x11),
    ("get-pbo-fused-slow-limit",           False, 0x12),
    ("get-pbo-fused-fast-limit",           False, 0x13),
    ("get-pbo-fused-apu-slow-limit",       False, 0x14),
    ("get-pbo-fused-vrmtdc-limit",         False, 0x15),
    ("get-pbo-fused-vrmsoc-current",       False, 0x16),
]

_CMD_FF3: list[tuple[str, bool, int]] = [
    ("enable-feature",                     True,  0x05),
    ("disable-feature",                    True,  0x07),
    ("stapm-limit",                        True,  0x14),
    ("stapm-limit",                        False, 0x31),
    ("stapm-time",                         True,  0x18),
    ("fast-limit",                         True,  0x15),
    ("slow-limit",                         True,  0x16),
    ("slow-time",                          True,  0x17),
    ("tctl-temp",                          True,  0x19),
    ("chtc-temp",                          False, 0x37),
    ("apu-skin-temp",                      True,  0x33),
    ("vrm-current",                        True,  0x1a),
    ("vrmmax-current",                     True,  0x1c),
    ("vrmsoc-current",                     True,  0x1b),
    ("vrmsocmax-current",                  True,  0x1d),
    ("vrmcvip-current",                    True,  0x1d),
    ("vrmgfx-current",                     True,  0x1e),
    ("vrmgfxmax-current",                  True,  0x1f),
    ("prochot-deassertion-ramp",           True,  0x22),
    ("gfx-clk",                            False, 0x89),
    ("gfx-clk",                            False, 0x1c),
    ("power-saving",                       True,  0x12),
    ("max-performance",                    True,  0x11),
    ("set-coall",                          True,  0x4c),
    ("set-coall",                          False, 0x5d),
    ("set-coper",                          True,  0x4b),
    ("set-cogfx",                          False, 0xb7),
    ("get-sustained-power-and-thm-limit",  True,  0x54),
    ("skin-temp-limit",                    True,  0x4a),
    ("apu-slow-limit",                     True,  0x23),
]

_CMD_FT6_FP7_FP8: list[tuple[str, bool, int]] = [
    ("enable-feature",                     True,  0x05),
    ("disable-feature",                    True,  0x07),
    ("stapm-limit",                        True,  0x14),
    ("stapm-limit",                        False, 0x31),
    ("stapm-time",                         True,  0x18),
    ("stapm-time",                         False, 0x36),
    ("fast-limit",                         True,  0x15),
    ("fast-limit",                         False, 0x32),
    ("slow-limit",                         True,  0x16),
    ("slow-limit",                         False, 0x33),
    ("slow-time",                          True,  0x17),
    ("slow-time",                          False, 0x35),
    ("tctl-temp",                          True,  0x19),
    ("chtc-temp",                          True,  0x63),
    ("chtc-temp",                          False, 0x37),
    ("vrm-current",                        True,  0x1a),
    ("vrm-current",                        False, 0x38),
    ("vrmmax-current",                     True,  0x1c),
    ("vrmmax-current",                     False, 0x3a),
    ("vrmsoc-current",                     True,  0x1b),
    ("vrmsoc-current",                     False, 0x39),
    ("vrmsocmax-current",                  True,  0x1d),
    ("vrmsocmax-current",                  False, 0x3b),
    ("psi0-current",                       True,  0x1e),
    ("psi0-current",                       False, 0x3c),
    ("psi0soc-current",                    True,  0x1f),
    ("psi0soc-current",                    False, 0x3d),
    ("psi3cpu-current",                    True,  0x20),
    ("psi3gfx-current",                    True,  0x21),
    ("prochot-deassertion-ramp",           True,  0x22),
    ("skin-temp-limit",                    True,  0x4a),
    ("apu-slow-limit",                     True,  0x23),
    ("apu-slow-limit",                     False, 0x34),
    ("apu-skin-temp",                      True,  0x33),
    ("apu-skin-temp",                      False, 0x91),
    ("dgpu-skin-temp",                     True,  0x34),
    ("dgpu-skin-temp",                     False, 0x92),
    ("max-performance",                    True,  0x11),
    ("power-saving",                       True,  0x12),
    ("enable-oc",                          False, 0x17),
    ("disable-oc",                         False, 0x18),
    ("oc-clk",                             False, 0x19),
    ("per-core-oc-clk",                    False, 0x1a),
    ("oc-volt",                            False, 0x1b),
    ("gfx-clk",                            False, 0x89),
    ("gfx-clk",                            False, 0x1c),
    ("pbo-scalar",                         False, 0x3e),
    ("get-pbo-scalar",                     False, 0x0f),
    ("set-cogfx",                          False, 0xb7),
    ("set-coper",                          True,  0x4b),
    ("set-coper",                          False, 0x53),
    ("set-coall",                          True,  0x4c),
    ("set-coall",                          False, 0x5d),
    ("get-coper-options",                  False, 0xe1),
    ("get-sustained-power-and-thm-limit",  True,  0x5f),
    ("get-pbo-fused-power-limit",          False, 0x11),
    ("get-pbo-fused-slow-limit",           False, 0x12),
    ("get-pbo-fused-fast-limit",           False, 0x13),
    ("get-pbo-fused-apu-slow-limit",       False, 0x14),
    ("get-pbo-fused-vrmtdc-limit",         False, 0x15),
    ("get-pbo-fused-vrmsoc-current",       False, 0x16),
    ("get-pbo-fused-tctl-temp",            False, 0xe5),
]

_CMD_AM5_V1: list[tuple[str, bool, int]] = [
    ("enable-feature",                     True,  0x03),
    ("disable-feature",                    True,  0x04),
    ("stapm-limit",                        True,  0x4f),
    ("stapm-time",                         True,  0x53),
    ("fast-limit",                         True,  0x3e),
    ("slow-limit",                         True,  0x5f),
    ("slow-limit",                         False, 0xcb),
    ("slow-time",                          True,  0x60),
    ("vrm-current",                        True,  0x3c),
    ("vrm-current",                        False, 0x57),
    ("ppt-limit",                          True,  0x3e),
    ("ppt-limit",                          False, 0x56),
    ("tdc-limit",                          True,  0x3c),
    ("tdc-limit",                          False, 0x57),
    ("edc-limit",                          True,  0x3d),
    ("edc-limit",                          False, 0x58),
    ("tctl-temp",                          True,  0x3f),
    ("tctl-temp",                          False, 0x59),
    ("pbo-scalar",                         False, 0x5b),
    ("oc-clk",                             False, 0x5f),
    ("per-core-oc-clk",                    False, 0x60),
    ("oc-volt",                            False, 0x61),
    ("set-coall",                          False, 0x07),
    ("set-coall",                          True,  0x36),
    ("set-coper",                          False, 0x06),
    ("set-coper",                          True,  0x35),
    ("set-cogfx",                          False, 0xa7),
    ("enable-oc",                          False, 0x5d),
    ("disable-oc",                         False, 0x5e),
    ("disable-prochot",                    False, 0x5d),
    ("skin-temp-limit",                    True,  0x5e),
    ("apu-slow-limit",                     True,  0x60),
    ("vrmmax-current",                     True,  0x3d),
    ("vrmmax-current",                     False, 0x58),
    ("chtc-temp",                          False, 0x59),
    ("get-pbo-scalar",                     False, 0x6d),
    ("set-boost-limit-frequency",          True,  0x2b),
    ("set-vddoff-vid",                     True,  0x4b),
    ("set-fll-btc-enable",                 True,  0x37),
    ("get-sustained-power-and-thm-limit",  True,  0x23),
    ("get-overclocking-support",           False, 0x6f),
    ("get-max-cpu-clk",                    False, 0x6e),
    ("get-min-gfx-clk",                    False, 0xce),
    ("get-max-gfx-clk",                    False, 0xcf),
    ("get-curr-gfx-clk",                   False, 0xd8),
    ("get-coper-options",                  False, 0xd5),
    ("get-cogfx-options",                  False, 0xd7),
    ("get-pbo-fused-vrmsoc-current",       False, 0xd9),
    ("get-pbo-fused-vrmtdc-limit",         False, 0xdb),
    ("get-pbo-fused-slow-limit",           False, 0xdc),
    ("get-pbo-fused-apu-slow-limit",       False, 0xda),
    ("get-pbo-fused-tctl-temp",            False, 0xde),
]

_SOCKET_COMMANDS: dict[str, list[tuple[str, bool, int]]] = {
    SOCKET_AM4_V1:      _CMD_AM4_V1,
    SOCKET_FT5_FP5_AM4: _CMD_FT5_FP5_AM4,
    SOCKET_AM4_V2:      _CMD_AM4_V2,
    SOCKET_FP6_AM4:     _CMD_FP6_AM4,
    SOCKET_FF3:         _CMD_FF3,
    SOCKET_FT6_FP7_FP8: _CMD_FT6_FP7_FP8,
    SOCKET_AM5_V1:      _CMD_AM5_V1,
}

_LOOKUP: dict[str, dict[str, list[tuple[bool, int]]]] = {}
for _s, _cmds in _SOCKET_COMMANDS.items():
    _d: dict[str, list[tuple[bool, int]]] = {}
    for _n, _m, _o in _cmds:
        _d.setdefault(_n, []).append((_m, _o))
    _LOOKUP[_s] = _d
del _s, _cmds, _d, _n, _m, _o

_ALL_KNOWN_ARGS: frozenset[str] = frozenset(
    n for cmds in _SOCKET_COMMANDS.values() for n, _, _ in cmds
)

_FLAG_ARGS: frozenset[str] = frozenset({
    "enable-oc", "disable-oc", "power-saving", "max-performance",
    "disable-prochot", "setcpu-freqto-ramstate", "stopcpu-freqto-ramstate",
    "set-fll-btc-enable",
})

def get_socket(family: str) -> str | None:
    return _FAMILY_SOCKET.get(family)


def lookup(family: str, arg_name: str) -> list[tuple[bool, int]]:
    sock = _FAMILY_SOCKET.get(family)
    if not sock:
        return []
    norm = arg_name.lstrip("-").replace("_", "-").lower()
    return _LOOKUP.get(sock, {}).get(norm, [])


def get_supported_args(family: str) -> list[str]:
    sock = _FAMILY_SOCKET.get(family)
    return list(_LOOKUP.get(sock, {}).keys()) if sock else []


def is_supported(family: str) -> bool:
    return get_socket(family) is not None and bool(get_supported_args(family))


def all_known_args() -> frozenset[str]:
    return _ALL_KNOWN_ARGS


def is_flag_arg(arg_name: str) -> bool:
    norm = arg_name.lstrip("-").replace("_", "-").lower()
    return norm in _FLAG_ARGS or norm.startswith("get-")
